# Generated by Django 2.1.1 on 2018-10-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20181015_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='agreeableness',
            field=models.DecimalField(decimal_places=6, max_digits=7),
        ),
        migrations.AlterField(
            model_name='entries',
            name='analytical',
            field=models.DecimalField(decimal_places=6, max_digits=7),
        ),
        migrations.AlterField(
            model_name='entries',
            name='anger',
            field=models.DecimalField(decimal_places=6, max_digits=7),
        ),
        migrations.AlterField(
            model_name='entries',
            name='confident',
            field=models.DecimalField(decimal_places=6, max_digits=7),
        ),
        migrations.AlterField(
            model_name='entries',
            name='conscientiousness',
            field=models.DecimalField(decimal_places=6, max_digits=7),
        ),
        migrations.AlterField(
            model_name='entries',
            name='disgust',
            field=models.DecimalField(decimal_places=6, max_digits=7),
        ),
        migrations.AlterField(
            model_name='entries',
            name='emotional_range',
            field=models.DecimalField(decimal_places=6, max_digits=7),
        ),
        migrations.AlterField(
            model_name='entries',
            name='extraversion',
            field=models.DecimalField(decimal_places=6, max_digits=7),
        ),
        migrations.AlterField(
            model_name='entries',
            name='fear',
            field=models.DecimalField(decimal_places=6, max_digits=7),
        ),
        migrations.AlterField(
            model_name='entries',
            name='joy',
            field=models.DecimalField(decimal_places=6, max_digits=7),
        ),
        migrations.AlterField(
            model_name='entries',
            name='openness',
            field=models.DecimalField(decimal_places=6, max_digits=7),
        ),
        migrations.AlterField(
            model_name='entries',
            name='sadness',
            field=models.DecimalField(decimal_places=6, max_digits=7),
        ),
        migrations.AlterField(
            model_name='entries',
            name='tentative',
            field=models.DecimalField(decimal_places=6, max_digits=7),
        ),
    ]
