# Generated by Django 2.1.2 on 2018-11-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20181015_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='submission_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='entries',
            name='user_ID',
            field=models.CharField(max_length=100),
        ),
    ]
